# Kirurgia

## Plastiikka- ja yleiskirurgia 

### 01: Suturaatio

Ei kortteja vielä

### 02: Patit & iholuomet + Melanooma & muut ihosyövät {#Ihosyovat}

Suosittelen käymään luentodiat **Patit & iholuomet** sekä **Melanooma & muut ihosyövät** samassa yhteydessä, sillä ne käsittelevät samoja asioita. Kortit on myös tehty sillä logiikalla, että molemmat materiaalit on opiskeltu ennen kortteja. 

- Suosittelen myös lukemaan näitä: 

  - [Ihokasvaimen stanssibiopsia vai poisto kokonaan?](https://www.terveysportti.fi/apps/dtk/ltk/article/duo18406/)
  - [Melanooman Terveysportti-artikkeli](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt01386/)
  - [Melanooma (Patologia, Duodecim](https://www.oppiportti.fi/oppikirjat/pat00688)
  - [Basalioomat, okasolusyöpä ja sen esiasteet, miten hoidan?](https://www.terveysportti.fi/apps/dtk/ltk/article/duo11556/)
  - [Kansallinen ei-melanoottisten ihosyöpien hoito-ohjeistus](https://www.terveysportti.fi/apps/dtk/ltk/article/hsu00009)
  - [Pehmytkudoskasvaimet](https://www.oppiportti.fi/oppikirjat/pat00763)
  
## Gastrokirurgia 

### 01: Akuutti vatsa

Suosittelen käymään läpi kaikki seuraavat luennot/osiot luennoista samaan syssyyn: akuutti vatsa, haimaluennon akuutti pankreatiitti -osio, ikteerinen potilas -luennon (eli sappirakon, sappiteiden ja maksan kirurgiset sairaudet) sappikivitaudin osio ja koloproktologiaa TK-lääkäreille -luennon divertikuliittiosio. Kortit ovat myös tehty sillä ajatuksella, että kaikki ym. aiheet on opiskeltu läpikohtaisesti. 

-	Pelkkä akuutti vatsa -luento jättää monet aiheet liian nopeasti käsitellyiksi ja on järkevää ottaa kaikki luennon aiheet heti haltuun -> kannattaa käydä aiheiden omat luennot läpi samalla 

  - Ym. luentojen loput aiheet ovat omissa tageissaan
  
Lisäksi suosittelen lukemaan/katsomaan seuraavia:

- [Appendisiitti Oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00574) ja [Appendisiitti Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt01830/)
  -	Käyn appendisiittia läpi myös yhdellä [opetusvideollani](https://youtu.be/gaZSuMsmqxs?si=PzhfOyi5jeTcGUZ0)
- [Divertikuliitti Oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00578) ja [Divertikuliitti Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00252)
  -	Käyn saman aiheen läpi myös yhdellä [opetusvideollani](https://youtu.be/DiQRv9rV0MM?si=rQVCLc2kcOdz_fE8&t=333) 
- [Sappikivitauti Oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00627) ja [Sappikivitauti Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00265/)
- [Pankreatiitti oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00634)
  -	[Pankreatiitin tyypeistä ja komplikaatioista todella selkeää tekstiä](https://radiologyassistant.nl/abdomen/pancreas/acute-pancreatitis)
  -	[Haiman kystisistä muutoksista samalta sivustolta](https://radiologyassistant.nl/abdomen/pancreas/pancreas-cystic-lesions)
- [Vatsavammat oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00537)
- [Ohutsuolitukos Oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00569) ja [Ohutsuolitukos Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00251/)
- [Ruokatorven puhkeama oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00549)

### 02: Ikteerinen potilas (sappirakon, sappiteiden ja maksan kirurgiset sairaudet) 

Diat käytännössä riittävät. Aikaisempien akuuttiin vatsaan liittyvien korttien lisäksi tägin alla on myös loput luentoon liittyvät kortit. 

### 03: Haimaluento 

Diat käytännössä riittävät. Aikaisempien akuuttiin vatsaan liittyvien korttien lisäksi tägin alla on myös loput luentoon liittyvät kortit. 

- [Täältä](https://www.oppiportti.fi/oppikirjat/kia00634) eteenpäin kannattaa lukea haiman sairauksista kuten aiemminkin

### 04: Mahasuolikanavan verenvuodot

Diat keskittyvät vain hyvin simppeliin GI-vuotojen lähestymistapaan eikä vuotojen akuutin diagnostiikan tai akuutin tilan hoidon lisäksi käydä läpi muuta. Tein kortit myös tähän malliin, joten kortteja on vähän ja diat riittävät niihin. 

- Jos haluaa perehtyä yksittäisiin aiheisiin enemmän, niin esim. sisuksilta Eso-Gas-Duo luento ja sen kortit sekä SketchyIM:n GI-videot (esim. varixvuodot) voivat olla hyvä lisä. 

### 05: Hälyttävät oireet ja GI-kanavan maligniteetit {#Halyttavat-oireet-ja-GI-kanavan-maligniteetit}

Luennon nimi on "Mitä hälyttävien oireiden takana voi olla – gi-kanavan maligniteeteista". Dioissa sinänsä kaikki riittävä aivan perusasioiden suhteen. Suositeltuja lisämateriaaleja:

- [Mahasyöpä Oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00557)
- [Ruokatorvisyöpä Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt02084/)
- [Kaikki kolorektaalikasvaimista Kirurgian oppikirjasta](https://www.oppiportti.fi/oppikirjat/kia00586)
- [Kolorektaalisyöpä Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt01866/)
- [Kolorektaalisyövän kansalliset hoitosuositukset](https://www.terveysportti.fi/apps/dtk/ltk/article/hsu00007/)

Ei kovinkaan hoitoon keskittyen, mutta kaikkeen sitä ennen: 

- [Mahalaukun syövät patologian opetusvideostani](https://youtu.be/4JpulGfwCh4?si=EjwC-_iyRZzDXHXz&t=2784)
- [Ruokatorven syövät patologian opetusvideostani](https://youtu.be/adbNA6vdZLQ?si=FLZq-7btXuJbj_6l&t=1683)
- [Paksusuolen polyypit ja kolorektaalikarsinooma -opetusvideo](https://youtu.be/4VHXfISmPto?si=FOxG6WXaWu3uWGwI)

## Propedeuttinen kirurgia 

## Thorax- ja verisuonikirurgia

### 01: Alaraajojen tukkiva valtimotauti (ASO-tauti)

Diat riittävät. Kannattaa kuitenkin silmäillä [Käypä Hoitoa](https://www.kaypahoito.fi/hoi50083) aiheesta. 

- Samasta aiheesta on myös ihan käypiä Sketchy-videoita: 

  - SketchySurgery -> Vascular disorders -> Peripheral -> Lower Extremity Peripheral Arterial Disease 1: Presentation & Workup + Lower Extremity Peripheral Arterial Disease 2: Management

### 02: Muu valtimokirurgia

Diat riittänevät pääosin. Voi lisäksi lueskella/katsoa: 

- [Kylmä jalka -artikkeli](https://trepo.tuni.fi/bitstream/handle/10024/222111/duo16892.pdf)
- [Aortan aneurysmat ja dissekoituma Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00159)
- [Subclavian steal syndrome](https://youtu.be/ry5fB1kMwyY?si=YYM8j-NQj2Ws_wNN)
- [Mesenteriaali-iskemiasta artikkeli](https://www.terveysportti.fi/apps/dtk/ltk/article/sll51002/)
- Aiheisiin liittyvät Sketchyt

## Urologia 

**Huom! Diat yleisesti aika heikkoja. Kannattaa todellakin lukea lisämateriaaleja.**

### 01: Virtsateiden toiminnalliset häiriöt {#Virtsateiden-toiminnalliset-hairiot}

Käy läpi "Urologisen potilaan tutkiminen"- ja "Virtsateiden toiminnalliset häiriöt"-luennot. Lisäksi: 

- [Inkontinenssi-video](https://youtu.be/Vli_6spE8HY?si=DMgq-x4hyavj92bL)
- [Prostatiitti Urokirjasta](https://www.oppiportti.fi/oppikirjat/uro02102)
- [BPH Urokirjasta](https://www.oppiportti.fi/oppikirjat/uro02200)
- [BPH Kirrakirjasta](https://www.oppiportti.fi/oppikirjat/kia00306)

### 02: Päivystysurologiaa {#Paivystysurologiaa}

Diojen lisäksi: 

- [Prostatiitti Urokirjasta](https://www.oppiportti.fi/oppikirjat/uro02102)
- [VTI Käypä Hoito](https://www.kaypahoito.fi/hoi10050) jos päässyt sisuksilta unohtumaan
- [Kiveskiertymä Kirran kirjasta](https://www.oppiportti.fi/oppikirjat/kia00290)
- [Virtsakivitauti Urokirjasta](https://www.oppiportti.fi/oppikirjat/uro01600) ja [Terveysportista](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt00303)

### 03: Eturauhassyövän diagnostiikka {#Eturauhassyovan-diagnostiikka}

Diojen lisäksi: 

- [Eturauhassyövän hoitoketjua](https://www.pirha.fi/web/hoito-ja-palveluketjut/eturauhassyopapotilaan-hoitoketju)
- [Eturauhassyöpä kirrakirjasta](https://www.oppiportti.fi/oppikirjat/kia00313)
- [PSA-seulonta](https://www.terveysportti.fi/apps/dtk/ltk/article/ykt02036/)

### 04: Eturauhassyövän hoito {#Eturauhassyovan-hoito}

Diojen lisäksi: 

- [Eturauhassyövän hoitoketjua](https://www.pirha.fi/web/hoito-ja-palveluketjut/eturauhassyopapotilaan-hoitoketju)
- [Eturauhassyöpä kirrakirjasta](https://www.oppiportti.fi/oppikirjat/kia00313)
  
  
### 05: Kivespussin sairaudet 

Paljon samoja aiheita kuin päivystysurologia-luennon korteissa ja samat kortit tägätty tännekin. Diojen lisäksi 

- [Hydroseele, spermatoseele, varikoseele](https://www.oppiportti.fi/oppikirjat/kia00334)
