# Anestesiologia ja tehohoito 

Ennakkomateriaalit ovat aika hyviä, niistä voi myös lueskella aiheita ennen kortteja. 

Tärpit uudelleenrakennettuna löytyy täältä: https://anetarpit.netlify.app/

## Sisäänpääsytentti 

[Jos koet tuen tarpeeksi](images/Sisäänpääsytentti_ANE.pdf)

## Elvytys 

Diojen lisäksi lue [elvytyksen Käypä Hoito](https://www.kaypahoito.fi/hoi17010)

## Akuuttihoidon ABCDE

Diat sinänsä riittävät, mutta suosittelen katsomaan SketchyIM:n Shock-videot läpi. 

## Yleisanestesia, sedaatio ja puudutukset 

Diat pääosin riittävät, kannattaa kerrata seuraavia jos päässyt unohtumaan:

- Pahoinvointilääkkeet: SketchyPharm Antiemetics 
- Farmiksen luennot samoista aiheista ([Yleisanestesia-aineet (Saari)](images/250313_Yleisanestesia-aineet_Saari.pdf) ja [Puudutteet (Hynninen)](images/250312_Puudutusaineet_Hynninen.pdf))

## Monitorointi

Diojen lisäksi suosittelen: 

- [Keskuslaskimokatetrit-verkkokurssi](https://www.oppiportti.fi/dvk00057) (diapakettissa vain yksi dia aiheesta, mutta tärpeissä pari kysymystä näihin liittyen; ei tarvitse verkkokurssia tarkasti käydä läpi, mutta perusidea aiheesta)
- [Kapnografia-video](https://youtu.be/fLfHsuWYbdc?si=x942lC9NxLq4E7Ca)
- [TOF artikkelimuodossa]( https://say.fi/files/illman_relaksaatio.pdf ) tai [videomuodossa](https://youtu.be/b61fpDNZOcU?si=VxuzU94RuK7FemSP) ja [videomuodossa tarkemmin](https://youtu.be/kqUAgtV3Bb4?si=cdcMjGGZh-usSWY0)

## Kivun hoito 

Diat + kivun hoito -seminaareihin liittyvät jutut riittävät, jos farmis on muuten hallussa. Jos haluaa virkistää muistiaan, niin kannattaa katsoa lääkeryhmien Sketchyt (samoja käsittelevät kortit myös tägätty tähän tägiin, jotta ns. pakosti tulee kerrattua tärkein farmakologia): 

- Blood&Inflammation::Anti-inflammatory::NSAIDs
- Neuro&Psych::Anesthetics&Analgetics::Opiates, Naloxone, Naltrexone 
- Neuro&Psych::Mood_Stabilizers&Antiepileptic_drugs::Gabapentin&Pregabalin

## Leikkauskelpoisuuden arviointi 

Diat riittävät. 

## Tehohoidon perusteet

Diat pääasiassa riittävät. Luennolla ei oikein tule paljoa uutta ja tämän takia tägi koostuu pääasiassa jo aikaisemmin tehdyistä korteista (esim. sisukset sepsiksen suhteen ja laboratoriolääketiede happo-emästasapainohäiriöiden suhteen). 

- Happo-emästasapainot opetetaan yleislääkäreille tyypillisesti helpon kaavan kautta ja se perusjaottelu on jo useaan kertaan opetettu. Jos haluaa lukea aiheesta tarkemmin, niin [täällä](https://say.fi/files/reinikainen_na_in.pdf) on suomeksi dioissakin siteerattu artikkeli ja [täällä](https://eclinpath.com/chemistry/acid-base/strong-ion-approach/) englanniksi Strong Ion Approachista. Näihin ei paneuduta liikaa korteissakaan, koska peruslähestymistapa happo-emästasapainohäiriöihin on paljon helpompi ja toimii suurimmassa osassa tapauksista. 


