# Radiologia

Kurssimateriaalina toimii Kliininen radiologia -oppikirja, Natiivikuvia päivystäjälle -Moodlekurssi ja muutamat luentopaketit 

Tentin rakenne ollut viime vuodet samanlainen: n. 50 kysymystä, joista vain 25% kuvia ja joista n. puolet thx-kuvia. Kysymykset yleisesti helppoja ja tentit olleet hyvin tärppisiä. 

- Tenttiarkistossa ei kuitenkaan ole vastauksia kysymyksiin ja kysymykset välillä väärin kirjoitettuja tai muistettuja. Olen koittanut koota viime vuosien kysymykset ja niiden mahdolliset vastaukset selkeämpään [pdf-tiedostoon](images\RAD_Tärpit_Vastattuna.pdf), jota voi halutessaan käyttää. 


## 01_Radiologian perusteet 

Tägin kortit eivät perustu mihinkään yksittäiseen luentoon tai kirjan kappaleeseen, mutta käyvät läpi tärkeimmät asiat radiologian fysiikasta ja kontrastiaineista. 

- Kaikki osiosta [Radiologisen tutkimuksen perusteet, Kliininen radiologia(Duodecim)]( https://www.oppiportti.fi/oppikirjat/krd00101)
- [Säteilysuojelu ja optimointi](https://www.oppiportti.fi/oppikirjat/krd01601)
- Kaikki osiosta [Fysiikka ja tekniikka](https://www.oppiportti.fi/oppikirjat/krd01401)
  - Tärpeissä tästä aiheesta jonkin verran varsinkin MRI:n suhteen. Kts. seuraavat MRI-fysiikkaa käsittelevät videot, jos aihe ei oikein avaudu tekstin perusteella 
    - [MRI-laitteen perusteet yleisesti](https://youtu.be/NlYXqRG7lus?si=0o-82vXxfTGKE0dy)
    - [MRI-fysiikan nopeat perusteet](https://youtu.be/jLnuPKhKXVM?si=k_udyqRVppONFS6-)
    - [T1- ja T2-relaksaatio uudestaan jos ei auennut aikeammin]( https://youtu.be/qrR2yoRhAmY?si=u6-W2s1geVV3UNCs)
    - Uskomattoman hyvä video aiheesta [T1W, T2W, PDW](https://youtu.be/gGIycwtFOBk?si=8BQb1_Nr99oH0ns5)
    - [Inversiopulssit ja rasvan/nesteen nollaus kuvasta](https://youtu.be/Iln6_J3V514?si=yQey8LnZZLBjBHXS)
    - [Kemiallinen siirtymä](https://youtu.be/QsKpK1AvYRs?si=ophLln7CAY1NjMQO)
    -	[MRI:n oppimisen tukena radiologymasterclassin perusteet](https://www.radiologymasterclass.co.uk/tutorials/mri/mri_scan)
    -	[Täydentävät neuroradiologiset kuvantamismenetelmät, erityisesti fMRI](https://www.oppiportti.fi/oppikirjat/krd00612)
- Kaikki osiosta [Kontrastiaineet](https://www.oppiportti.fi/oppikirjat/krd01501)
  -	[Varjoaineiden käytöstä lisää ja suosituksia mm. lääketauotuksista ja nesteprofylaksiasta](https://diagnostiikka.hus.fi/documents/20117/87759/varjoaineet_rontgentutkimuksissa_aikuispotilailla_suositus_kaytosta.pdf)
- [Johdatus rtg-kuvaan, Natiivikuvia päivystäjälle](https://moodle.utu.fi/pluginfile.php/1843050/mod_resource/content/4/Johdatus%20rtg-kuvaan.pdf)

## 02_Thorax 

Jaettu eri osioihin, jotka voi halutessaan käydä yksitellen läpi.

### 01_Perusteet 

- Thorax, Rtg-kuvia päivystäjälle 
-[Thx-rtg:n anatomian opetusvideo](https://youtu.be/wI2wC-trYxM?si=_XUyMW96VZfJOVig)
- [Thoraxkuva ja sen tulkinta, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00301)
- [Thoraxin kuvantamismenetelmät, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00302)

### 02_Sydämen vajaatoiminta {#02-Sydamen-vajaatoiminta} 

Kaikki osiosta [Sydän ja verisuonet; Thoraxkuvaus](https://www.oppiportti.fi/oppikirjat/krd00402)

### 03_Thoraxin tulehdus 

[Thoraxin tulehdussairaudet, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00303)

### 04_Keuhkojen parenkyymitaudit

[Keuhkojen parenkyymitaudit, Kliinen radiologia](https://www.oppiportti.fi/oppikirjat/krd00304)

### 05_Thoraxin kasvaimet

[Thoraxin kasvaimet, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00305)

### 06_Ei-traumaattinen päivystysradiologia {#Thoraxin-ei-traumaattinen-paivystysradiologia}

[Ei-traumaattinen päivystysradiologia, Thorax; Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00214)

### 07_Traumaattinen {#Thoraxin-traumaattinen-paivystysradiologia}

[Traumaattinen päivystysradiologia, Thorax; Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00205)

### 08_Tehohoitopotilaan radiologia

- Thorax- Rtg-kuvia päivystäjälle (johdot yms) 
- [Tehohoitopotilaan radiologiset tutkimukset, Thoraxkuvaus; Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00221)

## 03_Proksimaalinen yläraaja {#Proksimaalinen-ylaraaja}

### 01_Perusteet

Olkanivel, rtg-kuvia päivystäjälle 

### 02_Olkapää {#Olkapaa}

Yläraaja-luento

- Olkanivel, rtg-kuvia päivystäjälle 
- [Lapaluu - olkavarsi, Yläraaja-Trauman päivystysradiologia; Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00210)

### 03_Kyynärpää {#Kyynarpaa}

Yläraaja-luento

- Kyynärnivel, rtg-kuvia päivystäjälle
- [Kyynärpää ja kyynärvarsi, Yläraaja-Trauman päivystysradiologia; Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00210)

## 05_Ranne

Rannemurtumat luennosta Traumaradiologia

- [Röntgenkuvan anatomia ja mittaukset, Youtube](https://youtu.be/EvRBmngKJUU?si=ufp82RDKBFJk2Adr)
- Värttinäluun murtuman mittaaminen (Käsikirurgia Tietoisku 5)
- Ranne, Rtg-kuvia päivystäjälle
- [Ranne, Kliininen radiologia -oppikirja](https://www.oppiportti.fi/oppikirjat/krd00210)
- Kpl 38.2 ja 38.3 Traumatologia, Kandidaattikustannus
- Lapsen rannevamman RTG (Käsikirurgia tietoisku 1)


## 06_Käsi {#Kasi}

[Kämmenluut ja sormet, Kliininen radiologia -oppikirja](https://www.oppiportti.fi/oppikirjat/krd00210)

- Käden trauma rtg; Rtg-kuvia päivystäjälle

## 07_Lantio- ja lonkka

[Lantio ja lonkkamalja, Kliininen radiologia (Trauman päivystysradiologia)](https://www.oppiportti.fi/oppikirjat/krd00208) + [Alaraaja (Reisiluun proksimaaliosa)](https://www.oppiportti.fi/oppikirjat/krd00211#s1)

- Lonkka, rtg-kuvia päivystäjälle


## 08_Polvi

Polvi, rtg-kuvia päivystäjälle

- [Polvi osiosta Alaraaja, Kliininen radiologia -oppikirja](https://www.oppiportti.fi/oppikirjat/krd00211)

## 09_Nilkka

Nilkka, rtg-kuvia päivystäjälle

- [Nilkka osiosta Alaraaja, Kliininen radiologia -oppikirja](https://www.oppiportti.fi/oppikirjat/krd00211)

## 10_Jalkaterä

Jalkaterä, rtg-kuvia päivystäjälle

- [Kaikki nilkan jälkeen osiosta Alaraaja, Kliininen radiologia -oppikirja](https://www.oppiportti.fi/oppikirjat/krd00211)

## 11_Tuki-ja liikuntaelimet 

Kaikki kyseisestä [kirjan kappaleesta](https://www.oppiportti.fi/oppikirjat/krd00501)

## 12_Rankamurtumat 

Traumaradiologialuennosta rankaan liittyvät diat ja lisäksi: 

- [Selkärangan päivystyskuvantaminen, Kliininen radiologia -oppikirja](https://www.oppiportti.fi/oppikirjat/krd00207)
- Selkärangan vammat Ortopedian ja traumatologian luennoista voi selventää (samat kortit sielläkin siis)

## 13_Rinnat_ja_gynekologinen kuvantaminen

[Rinnat, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00901)

## 14_Lapset 

[Lasten murtumat, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00218)

- Yläraajaluennossa myös hyvin selitetty kasvutumakkeista 

## 15_Pään vammat ja infarktit {#Paan-vammat-ja-infarktit}

Luento riittää (samalla nimellä kuin tägi)

## 16_Pään ja selkäytimen elektiivinen radiologia {#Paan-ja-selkaytimen-selektiivinen radiologia}

Ei sinänsä tarvitse lukea mitään, mutta nämä kannattaa silmäillä

- Kirjasta osiot Aivojen kuvantaminen ja Selkäydin ja spinaalikanava pääkappaleesta [Pään, kaulan ja selkäytimen radiologia](https://www.oppiportti.fi/oppikirjat/krd00602)

## 17_Kasvot ja kaula 

Ei taaskaan oikein tarvitse lukea, mutta voi silmäillä:

- [Kasvojen trauma, Kliininen radiologia](https://www.oppiportti.fi/oppikirjat/krd00203)
- Kaikki osiosta [Pää, kasvot ja kaula](https://www.oppiportti.fi/oppikirjat/krd00607)

## 19_Vatsa 

- [Vatsan alueen trauma](https://www.oppiportti.fi/oppikirjat/krd00206)
- [Akuutti vatsa](https://www.oppiportti.fi/oppikirjat/krd00212)
- Kaikki osiosta [Vatsan radiologia](https://www.oppiportti.fi/oppikirjat/krd00701)

## 20_Toimenpiteet 

Ei tarvitse oikein lukea mitään, mutta voi silmäillä

- Kaikki osiosta [Päivystysradiologiset toimenpiteet ja indikaatiot](https://www.oppiportti.fi/oppikirjat/krd00225)





